Repository Giunne/Giunne, pull requests merged in 2025-03, with the labels that each got.

#49 [feature] 로드맵 UI 화면 개발
  Giunne/common/src/commonMain/composeResources/drawable/icon_attach_money.xml
  Giunne/common/src/commonMain/composeResources/drawable/icon_check.xml
  Giunne/common/src/commonMain/composeResources/drawable/icon_exp.xml
  Giunne/common/src/commonMain/composeResources/drawable/icon_stage.xml
  Giunne/common/src/commonMain/composeResources/drawable/image_youtube.png
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/shape/GPSquircleShapeWithBorder.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/BorderContentField.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/DrawExerciseLine.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/DrawJoggingLine.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/ExerciseActionButtons.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/ExerciseDescription.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/ExerciseHeaderLink.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/ExerciseRewardSection.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/ExerciseStep.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/RoadMapDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/RoadMapDialogEditable.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/RoadMapExerciseStage.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/dummy/TestData.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/node/MapNode.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/node/RoadMapStepsData.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/state/ExerciseUiState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/state/JoggingUiState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/state/RoadMapUiState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/student/ExerciseRoadmapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/student/JoggingRoadmapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/student/StudentRoadmapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/ui/theme/GPColor.kt
Labels: 🖥️ 클라이언트, ✨ 기능

#54 [feat] UI 일부 편의성 추가 및 수정 & 안드로이드 백스택 관리
  Giunne/android/src/main/AndroidManifest.xml
  Giunne/common/build.gradle.kts
  Giunne/common/src/androidMain/kotlin/com/project/giunne/common/presentation/common/player/ImageViewer.android.kt
  Giunne/common/src/androidMain/kotlin/com/project/giunne/common/presentation/common/player/VideoPlayer.android.kt
  Giunne/common/src/androidMain/kotlin/com/project/giunne/common/util/ZoomUtil.android.kt
  Giunne/common/src/androidMain/res/raw/giwoonnae_intro.mp4
  Giunne/common/src/commonMain/composeResources/drawable/icon_check.xml
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/AuthRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/AuthService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DefineUrl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/TokenHandler.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/UseCaseModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/AuthRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/auth/ChangePasswordUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/player/VideoPlayer.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/GradeDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/StudentCommentItemRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/StudentCommunityCommentColumn.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/TeacherCommentItemRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/TeacherCommunityCommentColumn.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/StudentCommunityDetailScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/dummy/CommentTestData.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/teacher/TeacherCommunityDetailScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/splash/SplashScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/teacher/TeacherMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/signup/SignupScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/signup/intent/InfoStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/signup/state/InfoState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/ui/theme/GPColor.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/StringUtil.kt
  Giunne/common/src/desktopMain/kotlin/com/project/giunne/common/presentation/common/player/ImageViewer.desktop.kt
  Giunne/common/src/desktopMain/kotlin/com/project/giunne/common/presentation/common/player/VideoPlayer.desktop.kt
  Giunne/common/src/desktopMain/kotlin/com/project/giunne/common/presentation/common/player/video/frame/FrameContainer.kt
  Giunne/common/src/desktopMain/kotlin/com/project/giunne/common/presentation/common/player/video/frame/FramePlayer.kt
  Giunne/common/src/desktopMain/kotlin/com/project/giunne/common/presentation/common/player/video/source/DefaultControls.kt
  Giunne/common/src/desktopMain/kotlin/com/project/giunne/common/presentation/common/player/video/source/MidControls.kt
  Giunne/common/src/desktopMain/kotlin/com/project/giunne/common/presentation/common/player/video/source/PlayerSource.kt
Labels: 🖥️ 클라이언트, ⚡️ 수정, ✨ 기능

#55 [feature] 캐릭터정보 필요한 화면 연결
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/AvatarUserResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/NetworkModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/charactor/GPMainCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/charactor/GPShopCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/ResultRoadMapItem.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/StudentCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/home/StudentHomeComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/home/StudentHomeScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/join/StudentJoinRecreationComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/join/StudentJoinRecreationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/search/SearchRoadMapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/state/StudentHomeState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/state/StudentJoinState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/TeacherHomeScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/state/MyPageState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/StudentMyPageComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/StudentMyPageScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/content/MyPageCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/StudentSelectCharacterComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/StudentSelectCharacterScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/state/CharacterUiState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/ShopScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/ItemBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/intent/ShopStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/state/CharacterState.kt
Labels: 🖥️ 클라이언트, ✨ 기능

#57 [fix] 누락된 shop, mypage 수정 사항 적용
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/StudentMyPageComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/intent/ShopStore.kt
Labels: 🐛 버그

#58 [modify]: 서버 API 변경 -> 로드맵 참여중 리스트 pagination 추가
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/AvatarResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/AvatarUserListResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/AvatarUserResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/AvatarRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/AvatarService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/AvatarRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/avatar/GetUserAvatarListUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/StudentCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/home/StudentHomeComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/home/StudentHomeScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/join/StudentJoinRecreationComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/join/StudentJoinRecreationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/state/StudentHomeState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/state/StudentJoinState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/state/MyPageState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/StudentMyPageComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/StudentMyPageScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/ShopScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/intent/ShopStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/Define.kt
Labels: 🖥️ 클라이언트, ⚡️ 수정

#59 [fix]: 경험치 양 0 안되게 수정
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/AvatarResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/AvatarUserResponse.kt
Labels: 🖥️ 클라이언트, 🐛 버그

#67 [feat] 학생 인증 현황 조회
  Giunne/common/src/androidMain/kotlin/com/project/giunne/common/util/BackHandler.android.kt
  Giunne/common/src/commonMain/composeResources/drawable/icon_write.xml
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/QuestInfo.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/QuestUploadListInfo.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/StudentCourseResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/CertificationRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/CertificationService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DefineUrl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/RepositoryModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/ServiceModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/UseCaseModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/CertificationRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/certification/GetCertificationHistory.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/certification/GetCertificationProgress.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/StudentCertificationComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/StudentCertificationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RoadMapCertScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RoadmapCertProgressBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RoadmapDoneListItemRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/TeacherRoadMapCertScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/dummy/DoneDto.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/state/CertProgress.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/state/StudentCertificationState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/StudentCommunityDetailScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/intent/FriendStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/student/StudentFriendScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/teacher/TeacherFriendScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/login/LoginComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/login/LoginScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/common/NotificationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/dummy/NotificationTestData.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/teacher/TeacherMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notification/NotificationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notification/NotificationUtil.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notification/content/NotificationItem.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notification/state/NotificationState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/Define.kt
Labels: 🖥️ 클라이언트, ✨ 기능

#68 [feat] 선생님 화면 로그인 및 본인이 생성한 로드맵 검색
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/local/preference/SettingRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/RecreationStudentJoinResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/RecreationRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/RecreationService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DefineUrl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/UseCaseModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/RecreationRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/roadmap/GetRecreationStudentJoinUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/TeacherHomeComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/TeacherHomeScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/content/StudentSignUpCodeBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/recreation/TeacherRecreationComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/recreation/TeacherRecreationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/state/TeacherHomeState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/state/TeacherRecreationState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/teacher/TeacherMainComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/teacher/TeacherMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/Define.kt
Labels: 🖥️ 클라이언트, ✨ 기능

#72 [feat] 선생님 학생 채점 API 연결
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/request/GradeStudentRequest.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/CertificationRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/CertificationService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DefineUrl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/UseCaseModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/CertificationRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/certification/PostGradeStudentUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/intent/CommunityStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/intent/GradeStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/state/GradeState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/teacher/TeacherCommunityDetailScreen.kt
Labels: 🖥️ 클라이언트, ✨ 기능

#74 [feat] 로드맵 영상 및 사진 업로드 API 추가
  Giunne/common/src/androidMain/kotlin/com/project/giunne/common/presentation/common/picker/ImagePicker.android.kt
  Giunne/common/src/androidMain/kotlin/com/project/giunne/common/presentation/common/picker/PlatformFile.android.kt
  Giunne/common/src/androidMain/kotlin/com/project/giunne/common/presentation/common/picker/VideoPicker.android.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/CertificationRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/CertificationService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DefineUrl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/NetworkModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/UseCaseModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/CertificationRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/certification/PostUploadFileUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/StudentCertificationComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/StudentCertificationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RoadMapCertScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RunningCertScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/UploadFileProgressDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/state/StudentCertificationState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/teacher/TeacherCertificationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/picker/PlatformFile.kt
  Giunne/common/src/desktopMain/kotlin/com/project/giunne/common/presentation/common/picker/PlatformFile.desktop.kt
  Giunne/common/src/desktopMain/kotlin/com/project/giunne/common/presentation/common/player/VideoPlayer.desktop.kt
Labels: 🖥️ 클라이언트, ✨ 기능

#77 [feat] 홈 화면 유틸리티 및 화면 이동 유틸리티 구현
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/StudentCourseResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/CommunityRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/CommunityService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/CommunityRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/community/GetPostingList.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/SearchRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/SelectableDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/StudentCommunityComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/StudentCommunityScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/state/DatePriority.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/state/StudentCommunityState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/state/TeacherCommunityState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/teacher/TeacherCommunityComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/teacher/TeacherCommunityScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/TeacherCheckingBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/home/StudentHomeComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/home/StudentHomeScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/state/StudentHomeState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/ExerciseActionButtons.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/RoadMapDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/student/ExerciseRoadmapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/student/StudentRoadmapScreen.kt
Labels: 🖥️ 클라이언트, ✨ 기능

#83 [feat] 댓글 삭제 기능 구현 및 아이디 중복 체크 구현
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/IDExistInfo.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/AuthRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/CommunityRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/AuthService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/CommunityService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DefineUrl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/UseCaseModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/AuthRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/CommunityRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/auth/CheckExistIdUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/community/DeleteComment.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/CommentInputRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/StudentCommentItemRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/StudentCommunityCommentColumn.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/TeacherCommentItemRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/TeacherCommunityCommentColumn.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/StudentCommunityDetailScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/intent/CommunityStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/teacher/TeacherCommunityDetailScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/ExerciseActionButtons.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/RoadMapDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/signup/SignupScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/signup/intent/InfoStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/signup/state/InfoState.kt
Labels: 🖥️ 클라이언트, ⚡️ 수정, ✨ 기능

#87 [feat] 선생님 학생들 개인 로드맵 열람 및 코인 수정 추가
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/request/StudentPointRequest.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/AvatarUserResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/AvatarRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/RoadMapRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/AvatarService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/RoadMapService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DefineUrl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/UseCaseModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/AvatarRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/RoadMapRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/avatar/ModifyStudentPointUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/roadmap/GetSpecificStudentCourseUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/CheckModifyPoint.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/StudentExerciseView.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/StudentJoggingView.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/StudentRoadMapDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/TeacherFriendItemRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/TeacherModifyStudentPoint.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/dummy/FriendsTestData.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/intent/FriendStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/state/FriendState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/student/StudentFriendScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/teacher/TeacherFriendScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/home/StudentHomeComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/TeacherHomeComponent.kt
Labels: 🖥️ 클라이언트, ✨ 기능

#89 [feat] 댓글 좋아요 보상 구현
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/request/CommentLikeRequest.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/AvatarUserResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/MyPointInfo.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/AvatarRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/AvatarService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DefineUrl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/UseCaseModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/AvatarRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/avatar/GetMyPointUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/SendLikeDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/intent/CommunityStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/state/CommunityState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/teacher/TeacherCommunityDetailScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/GachaScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/GachaButtonView.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/AvatarUtil.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/StringUtil.kt
Labels: 🖥️ 클라이언트, ✨ 기능

#90 [feat] 뽑기 화면 기능 추가
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/request/CommentLikeRequest.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/PossibleItemCountInto.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/AvatarRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/ShopRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/ShopService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DefineUrl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/UseCaseModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/ShopRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/shop/GetPossibleItemCountUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/StudentCommentItemRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/GachaScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/intent/GachaStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/state/GachaState.kt
Labels: 🖥️ 클라이언트, ⚡️ 수정, ✨ 기능

#91 [feat] 내 정보 수정 및 화면 추가
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/request/AvatarModifyRequest.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/AvatarInformationResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/MyPageRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/MyPageService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DefineUrl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/UseCaseModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/MyPageRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/mypage/GetAvatarInformationUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/mypage/ModifyAvatarInformationUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/TeacherHomeComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/intent/MyPageEvent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/state/MyPageState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/StudentMyPageComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/StudentMyPageScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/content/ModifyStudentInfoDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/content/MyPageStudentInfoColumn.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/teacher/TeacherMyPageComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/teacher/TeacherMyPageScreen.kt
Labels: 🖥️ 클라이언트, ✨ 기능

#93 [Fix] 앱 사용성 오류 1차 해결
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/AvatarInformationResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/DoneListBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RoadMapCertScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RunningCertScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/intent/FriendStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/teacher/TeacherMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/StudentMyPageScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/teacher/TeacherMyPageScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/DrawJoggingLine.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/DrawTeacherJoggingLine.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/teacher/TeacherExerciseRoadmapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/teacher/TeacherJoggingRoadmapScreen.kt
Labels: 🖥️ 클라이언트, 🐛 버그

#95 [fix] 앱 사용 오류 수정
  Giunne/android/src/main/AndroidManifest.xml
  Giunne/android/src/main/ic_launcher-playstore.png
  Giunne/android/src/main/res/drawable/ic_launcher_background.xml
  Giunne/android/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Giunne/android/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Giunne/android/src/main/res/mipmap-hdpi/ic_launcher.webp
  Giunne/android/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  Giunne/android/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Giunne/android/src/main/res/mipmap-mdpi/ic_launcher.webp
  Giunne/android/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  Giunne/android/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Giunne/android/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Giunne/android/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  Giunne/android/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Giunne/android/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Giunne/android/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  Giunne/android/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Giunne/android/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Giunne/android/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  Giunne/android/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Giunne/android/src/main/res/values/styles.xml
  Giunne/common/src/androidMain/kotlin/com/project/giunne/common/util/DpUtil.android.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/AvatarRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/CertificationRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/CommunityRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/MyPageRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/RecreationRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/RoadMapRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/ShopRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/TeacherRoadMapCertScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/TeacherRunningCertScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/teacher/TeacherCertificationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/EmptyBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/StudentCommunityCommentColumn.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/TeacherCommunityCommentColumn.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/TeacherFriendItemRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/dummy/FriendsTestData.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/student/StudentFriendScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/teacher/TeacherFriendScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/StudentRoadMapLevelBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/TeacherHomeScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/login/LoginScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/splash/SplashScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/teacher/TeacherMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/root/RootContent.kt
  Giunne/desktop/src/jvmMain/kotlin/Main.kt
Labels: 🖥️ 클라이언트, ⚡️ 수정, 🐛 버그

#97 [Fix] 앱 사용성 오류 2차 해결
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/QuestInfo.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/StudentCourseResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/StudentCertificationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RoadMapCertScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RoadmapCertBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RunningCertScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/StudentExerciseView.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/content/MyPageCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/RoadMapDialogEditable.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/student/ExerciseRoadmapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/teacher/TeacherExerciseRoadmapScreen.kt
Labels: 🖥️ 클라이언트, ⚡️ 수정, 🐛 버그
