Repository Giunne/Giunne, pull requests merged in 2025-04, with the labels that each got.

#99 [Fix] 앱 사용성 오류 3차 해결
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/PostingDetailResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/QuestInfo.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/NetworkModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/GradeDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/teacher/TeacherCommunityDetailScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/FriendAvatarDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/StudentExerciseView.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/StudentFriendItemRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/intent/FriendStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/state/FriendState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/student/StudentFriendScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/teacher/TeacherMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/AlreadyCheckedDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/student/ExerciseRoadmapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/teacher/TeacherExerciseRoadmapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/teacher/TeacherJoggingRoadmapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/teacher/TeacherRoadmapComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/teacher/state/RoadMapState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/StudentSelectCharacterComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/StudentSelectCharacterScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/state/CharacterUiState.kt
Labels: 🖥️ 클라이언트, ⚡️ 수정, ✨ 기능, 🐛 버그

#101 [Fix] 3차 앱 사용성 수정
  Giunne/android/build.gradle.kts
  Giunne/android/proguard-rules.pro
  Giunne/android/release/output-metadata.json
  Giunne/android/src/main/res/drawable/icon_vertical_more.xml
  Giunne/common/src/commonMain/composeResources/drawable/icon_vertical_more.xml
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/request/PasswordChangeRequest.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/request/StudentExpRequest.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/AuthRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/AvatarRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/AuthService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/AvatarService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DefineUrl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/UseCaseModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/AuthRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/AvatarRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/avatar/ChangeStudentPasswordUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/avatar/ModifyStudentExpUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/avatar/ResetPasswordUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/StudentCertificationComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/StudentCertificationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/teacher/TeacherCertificationComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/button/GPButton.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/StudentCommunityScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/teacher/TeacherCommunityScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/CheckModifyPoint.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/ModifyExpDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/ModifyPointDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/TeacherFriendItemRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/intent/FriendStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/state/FriendState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/teacher/TeacherFriendScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/TeacherHomeComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/TeacherHomeScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/content/RemainCheckingStudentBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/state/TeacherHomeState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/login/LoginComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/login/LoginScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/login/content/PasswordSetupDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/login/state/LoginState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/teacher/TeacherMainComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/teacher/TeacherMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/StudentJoggingActionButtons.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/StudentJoggingDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/student/StudentRoadmapScreen.kt
  Giunne/desktop/build.gradle.kts
  Giunne/desktop/giunne_icon.ico
  Giunne/desktop/giunne_installer_script.iss
  Giunne/desktop/proguard-rules.pro
  Giunne/gradle.properties
Labels: 🖥️ 클라이언트, ⚡️ 수정, ✨ 기능

#103 [Modify] 앱 사용 오류 수정 및 사용성 개선 3차
  Giunne/common/src/commonMain/composeResources/files/animation_success.json
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/local/preference/SettingRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/StudentCertificationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RoadmapCertConfirmDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/dialog/GPSuccessRoadMapDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/home/StudentHomeComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/home/StudentHomeScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/state/StudentHomeState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/DrawExerciseLine.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/DrawJoggingLine.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/RoadMapExerciseStage.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/student/JoggingRoadmapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/student/StudentRoadmapComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/student/StudentRoadmapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/student/state/StudentRoadMapState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/ui/theme/GPColor.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/Define.kt
Labels: 🖥️ 클라이언트, ⚡️ 수정, ✨ 기능

#105 [fix] 앱 사용성 추가
  Giunne/android/build.gradle.kts
  Giunne/android/release/output-metadata.json
  Giunne/android/src/main/AndroidManifest.xml
  Giunne/android/src/main/java/com/project/giunne/android/GPFirebaseMessagingService.kt
  Giunne/android/src/main/java/com/project/giunne/android/MainActivity.kt
  Giunne/build.gradle.kts
  Giunne/common/build.gradle.kts
  Giunne/common/src/androidMain/kotlin/com/project/giunne/common/util/PermissionUtil.android.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/AvatarUserResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/avatar/GetFriendsListUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/PageSelectRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RunningCertScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/GradeDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/StudentFriendItemRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/TeacherFriendItemRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/intent/FriendStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/TeacherHomeComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/teacher/TeacherExerciseRoadmapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/teacher/TeacherJoggingRoadmapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/LogUtil.kt
  Giunne/gradle.properties
  Giunne/gradle/libs.versions.toml
Labels: 🖥️ 클라이언트, ⚡️ 수정, ✨ 기능

#107 [feat] 공지사항 기능 추가
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/request/CreateNoticeRequest.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/request/ModifyNoticeRequest.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/NoticeListResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/UnreadNoticeCountResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/NoticeRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/NoticeService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DefineUrl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/RepositoryModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/ServiceModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/UseCaseModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/NoticeRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/notice/DeleteNoticeUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/notice/GetNoticeDetailUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/notice/GetNoticeListUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/notice/ModifyNoticeUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/notice/PostNoticeUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/notice/ReadNoticeUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/notice/UnreadNoticeCountUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/dialog/GPConfirmDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/join/StudentJoinRecreationComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/join/StudentJoinRecreationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/state/StudentJoinState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/recreation/TeacherRecreationComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/recreation/TeacherRecreationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/state/TeacherRecreationState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/dummy/NotificationTestData.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/teacher/TeacherMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notice/NoticeScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notice/content/CreateNoticeDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notice/content/EmptyList.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notice/content/ModifyCheckbox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notice/content/NoticeItem.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notice/content/NoticeTextField.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notice/content/StudentNoticeDetailDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notice/content/TeacherNoticeDetailDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notice/intent/NoticeStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notice/state/NoticeState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notification/NotificationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notification/NotificationUtil.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/notification/state/NotificationState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/ui/theme/GPColor.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/SnackbarUtil.kt
Labels: 🖥️ 클라이언트, ✨ 기능

#109 [feat] 알림 기능 구현
  Giunne/android/build.gradle.kts
  Giunne/android/release/output-metadata.json
  Giunne/android/src/main/java/com/project/giunne/android/GPFirebaseMessagingService.kt
  Giunne/android/src/main/java/com/project/giunne/android/MainActivity.kt
  Giunne/android/src/main/res/drawable/image_logo.png
  Giunne/common/build.gradle.kts
  Giunne/common/src/androidMain/res/drawable/image_logo.png
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/local/preference/SettingRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/request/FCMRequest.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/AuthResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/FCMResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/PostingDetailResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/AvatarRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/AvatarService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DefineUrl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/UseCaseModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/AvatarRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/avatar/GetFCMTokenListUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/avatar/PostFCMTokenUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/CommentInputRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/teacher/TeacherCommunityDetailScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/intent/FriendStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/ExpArrowPercent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/TeacherHomeComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/login/LoginComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/root/RootComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/root/RootContent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/PickingItemScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/Define.kt
  Giunne/common/src/desktopMain/kotlin/com/project/giunne/common/util/ScreenDpiUtil.kt
  Giunne/desktop/src/jvmMain/kotlin/Main.kt
  Giunne/desktop/src/jvmMain/kotlin/util/ScreenDpiUtil.kt
Labels: 🖥️ 클라이언트, ⚡️ 수정, ✨ 기능

#111 [fix] 토큰 대응 및 화면 비율 대응
  Giunne/android/release/output-metadata.json
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/AvatarRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/CertificationRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/CommunityRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/MyPageRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/RecreationRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/RoadMapRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/ShopRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/TokenHandler.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/charactor/GPMainCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/charactor/GPSmallCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/home/StudentHomeComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/teacher/TeacherMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/RoadMapExerciseStage.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/RoadMapTeacherExerciseStage.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/ItemBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/Define.kt
  Giunne/desktop/build.gradle.kts
  Giunne/desktop/src/jvmMain/kotlin/Main.kt
  Giunne/gradle.properties
Labels: ⚡️ 수정

#113 [fix] 앱 사용 오류 및 사용성 추가
  Giunne/android/release/output-metadata.json
  Giunne/common/src/commonMain/composeResources/files/animation_levelup.json
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/local/preference/SettingRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/AvatarUserResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/AvatarRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/avatar/GetFriendsListUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RoadMapCertScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RoadmapDoneListItemRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RunningCertScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/certification/student/content/RunningDoneListItemRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/charactor/GPMainCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/charactor/GPShopCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/charactor/GPSmallCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/dialog/GPLevelUpDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/student/StudentCommunityDetailScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/teacher/TeacherCommunityDetailScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/content/FriendAvatarDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/friend/intent/FriendStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/StudentCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/home/StudentHomeScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/join/StudentJoinRecreationComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/StudentMyPageScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/content/MyPageCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/RoadMapExerciseStage.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/content/RoadMapTeacherExerciseStage.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/teacher/TeacherExerciseRoadmapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/roadmap/teacher/TeacherJoggingRoadmapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/PickingItemScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/GachaItemList.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/ItemBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/signup/SignupScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/AvatarUtil.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/Define.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/StringUtil.kt
  Giunne/common/src/desktopMain/kotlin/com/project/giunne/common/presentation/common/player/ImageViewer.desktop.kt
  Giunne/desktop/build.gradle.kts
  Giunne/gradle.properties
Labels: 🖥️ 클라이언트, ⚡️ 수정, ✨ 기능, 🐛 버그
