Repository Giunne/Giunne, pull requests merged in 2025-02, with the labels that each got.

#25 [feat] 내정보 화면 UI 개발
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/common/RowWithDropShadow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/common/MyPageSettingInfo.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/StudentMyPageScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/content/MyPageCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/content/MyPageStudentInfoColumn.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/ui/theme/GPColor.kt
Labels: 🖥️ 클라이언트, ✨ 기능

#27 [feat] 상점 및 뽑기 UI 구현
  Giunne/common/build.gradle.kts
  Giunne/common/src/commonMain/composeResources/drawable/test_item_body.png
  Giunne/common/src/commonMain/composeResources/drawable/test_item_body1.png
  Giunne/common/src/commonMain/composeResources/drawable/test_item_body2.png
  Giunne/common/src/commonMain/composeResources/drawable/test_item_character.png
  Giunne/common/src/commonMain/composeResources/drawable/test_item_chracter_gacha.png
  Giunne/common/src/commonMain/composeResources/drawable/test_item_face.png
  Giunne/common/src/commonMain/composeResources/drawable/test_item_face2.png
  Giunne/common/src/commonMain/composeResources/drawable/test_item_head.png
  Giunne/common/src/commonMain/composeResources/drawable/test_item_head2.png
  Giunne/common/src/commonMain/composeResources/files/animation_box.json
  Giunne/common/src/commonMain/composeResources/files/animation_party_background.json
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/charactor/GPCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/StudentHomeScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/StudentCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/GachaScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/PickingItemScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/ShopComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/ShopScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/GachaButtonView.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/GachaItemList.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/ItemBottomView.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/ItemBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/ItemChipGroup.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/ItemGridList.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/ItemModifyBottomView.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/ItemPrice.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/LottieBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/MysteryBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/content/StudentRemainPoint.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/dummy/TestData.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/intent/ShopStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/state/CharacterState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/state/ItemType.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/ui/theme/GPColor.kt
  Giunne/gradle/libs.versions.toml
Labels: 🖥️ 클라이언트, ✨ 기능

#37 [feat] 네트워크 기본 세팅
  Giunne/build.gradle.kts
  Giunne/common/build.gradle.kts
  Giunne/common/src/commonMain/composeResources/values/string.xml
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/GachaResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/ShopRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/ShopService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/BaseResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DataThrowable.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DefineUrl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/ErrorMessages.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/NetworkHandler.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/NetworkResult.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/NetworkModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/RepositoryModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/ServiceModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/UseCaseModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/ShopRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/shop/GetGachaMapUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/teacher/TeacherMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/GachaScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/intent/GachaStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/shop/state/GachaState.kt
  Giunne/desktop/src/jvmMain/kotlin/Main.kt
  Giunne/gradle/libs.versions.toml
Labels: 🖥️ 클라이언트, ⚙️ 설정, ✨ 기능

#36 [feat] 학생 홈화면 추가 UI 개발
  Giunne/android/src/main/AndroidManifest.xml
  Giunne/common/src/commonMain/composeResources/drawable/icon_point_arrow.xml
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/dropdown/GPDropdownMenu.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/search/GPSearchBar.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/textfield/GPTextFieldWithClose.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/common/BorderButton.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/ExpArrowPercent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/LevelBadgeBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/ResultRoadMapItem.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/StudentCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/TeacherCheckingBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/home/StudentHomeComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/home/StudentHomeScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/search/SearchRoadMapComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/search/SearchRoadMapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/content/RemainCheckingStudentBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/content/StudentSignUpCodeBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/mypage/student/content/MyPageCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/StudentSelectCharacterComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/StudentSelectCharacterScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/content/SelectCharacterLabel.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/content/SelectCharacterPage.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/state/SelectCharacterUiState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/extension/Modifier.kt
Labels: 🖥️ 클라이언트, ✨ 기능

#39 [Modify]: merge 누락 부분 추가
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/StudentCharacter.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/TeacherCheckingBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/teacher/TeacherMainComponent.kt
Labels: 🖥️ 클라이언트, ⚡️ 수정

#46 [feat] 토큰 관리 및 자동 로그인 구현
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/local/preference/SettingRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/TokenHandler.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/community/content/CommentInputRow.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/login/LoginComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/signup/intent/InfoStore.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/util/Define.kt
Labels: 🖥️ 클라이언트, ✨ 기능

#47 [feature] 홈화면, 학생, 선생님 API 연결 및 화면 개발
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/request/AvatarCreateRequest.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/request/AvatarLoginRequest.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/request/RecreationRequest.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/AvatarResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/AvatarUserResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/PaginationInfo.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/RecreationCreateResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/RecreationSearchResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/RecreationStudentJoinResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/remote/response/SchoolListResponse.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/AvatarRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/repository/RecreationRepositoryImpl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/AvatarService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/service/RecreationService.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/data/util/DefineUrl.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/NetworkModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/RepositoryModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/ServiceModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/di/UseCaseModule.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/AvatarRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/repository/RecreationRepository.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/avatar/CreateAvatarUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/avatar/GetUserAvatarListUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/avatar/LoginRecreationUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/roadmap/CreateRecreationUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/roadmap/GetRecreationStudentJoinUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/domain/usecase/roadmap/GetSearchRecreationUseCase.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/dropdown/GPDropdownMenu.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/empty/GPResultEmpty.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/common/textfield/GPTextFieldWithClose.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/common/BorderButton.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/common/EmptyResult.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/ExpArrowPercent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/ResultRoadMapItem.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/content/TeacherCheckingBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/home/StudentHomeComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/home/StudentHomeScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/join/StudentJoinRecreationComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/join/StudentJoinRecreationScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/search/SearchRoadMapComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/search/SearchRoadMapScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/state/SearchRoadmapState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/state/StudentHomeState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/student/state/StudentJoinState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/TeacherEmptyHomeScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/TeacherHomeComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/TeacherHomeScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/content/RemainCheckingStudentBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/content/StudentSignUpCodeBox.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/content/TeacherCreateRoadmapDialog.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/home/teacher/state/TeacherHomeState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/student/StudentMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/main/teacher/TeacherMainScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/StudentSelectCharacterComponent.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/StudentSelectCharacterScreen.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/content/SelectCharacterPage.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/state/CharacterUiState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/select/state/SelectCharacterUiState.kt
  Giunne/common/src/commonMain/kotlin/com/project/giunne/common/presentation/signup/state/InfoState.kt
Labels: 🖥️ 클라이언트, ⚡️ 수정, ✨ 기능
